#!/bin/sh

# $1:       separator (use $'\n' for newline)
# $2..$end: strings to join
_join() {
	local separator="$1"
	shift
	(IFS="$separator"; echo -n "$*")
}

echo "User tor"
echo "Group tor"

[ -n "$TOR_DATADIRECTORY" ] && echo "DataDirectory $TOR_DATADIRECTORY" || echo "DataDirectory /var/tmp/tor"

[ "$TOR_SOCKS_PORT" ] && echo "SocksPort $TOR_SOCKS_PORT"
[ "$TOR_SOCKS_ADDRESS" ] && echo "SocksListenAddress $TOR_SOCKS_ADDRESS"

[ "$TOR_CONTROL_PORT" ] && echo "ControlPort $TOR_CONTROL_PORT"
[ "$TOR_CONTROL_ADDRESS" ] && echo "ControlListenAddress $TOR_CONTROL_ADDRESS"
[ "$TOR_CONTROL_HASHED_PASS" ] && echo "HashedControlPassword $TOR_CONTROL_HASHED_PASS"

[ "$TOR_CIRCUIT_IDLE_TIMEOUT" ] && echo "CircuitIdleTimeout $TOR_CIRCUIT_IDLE_TIMEOUT"

if [ "$TOR_SOCKS_POLICY_REJECT" != "no" ]; then
	_join $'\n' $(echo "$TOR_SOCKS_POLICY_ACCEPT" | grep -v "^#") | sed -e 's/^/SocksPolicy accept /'; echo
	echo "SocksPolicy reject *"
fi

[ -n "$TOR_ENTRY_NODES" ] && echo "EntryNodes $(_join ',' $(echo "$TOR_ENTRY_NODES" | grep -v "^#"))"
[ "$TOR_STRICT_ENTRY_NODES" == "yes" ] && echo "StrictEntryNodes 1"

[ -n "$TOR_EXIT_NODES" ] && echo "ExitNodes $(_join ',' $(echo "$TOR_EXIT_NODES" | grep -v "^#"))"
[ "$TOR_STRICT_EXIT_NODES" == "yes" ] && echo "StrictExitNodes 1"

if [ "$TOR_RELAY_ENABLED" == "yes" ]; then
	[ "$TOR_NICKNAME" ] && echo "Nickname $TOR_NICKNAME"
	[ "$TOR_ADDRESS" ] && echo "Address $TOR_ADDRESS"
	[ "$TOR_BANDWIDTHRATE" ] && echo "BandwidthRate $TOR_BANDWIDTHRATE"
	[ "$TOR_BANDWIDTHBURST" ] && echo "BandwidthBurst $TOR_BANDWIDTHBURST"
	[ "$TOR_ORPORT" ] && echo "ORPort $TOR_ORPORT"
	[ "$TOR_DIRPORT" ] && echo "DirPort $TOR_DIRPORT"
	[ "$TOR_MAXONIONSPENDING" ] && echo "MaxOnionsPending $TOR_MAXONIONSPENDING"
	[ "$TOR_EXITPOLICY" ] && echo "ExitPolicy $TOR_EXITPOLICY"
	[ "$TOR_BRIDGERELAY" == "yes" ] && echo "BridgeRelay 1"
fi

[ "$TOR_GEOIP_FILE" ] && echo "GeoIPFile $TOR_GEOIP_FILE.IPv4"
[ "$TOR_GEOIP_FILE" ] && echo "GeoIPv6File $TOR_GEOIP_FILE.IPv6"

[ "$TOR_TRANS_PORT" ] && echo "TransPort $TOR_TRANS_PORT"
[ "$TOR_TRANS_ADDRESS" ] && echo "TransListenAddress $TOR_TRANS_ADDRESS"

[ "$TOR_NATD_PORT" ] && echo "NATDPort $TOR_NATD_PORT"
[ "$TOR_NATD_ADDRESS" ] && echo "NATDListenAddress $TOR_NATD_ADDRESS"

[ "$TOR_DNS_PORT" ] && echo "DNSPort $TOR_DNS_PORT"
[ "$TOR_DNS_ADDRESS" ] && echo "DNSListenAddress $TOR_DNS_ADDRESS"


[ "$TOR_VIRTUAL_ADDR_NETWORK" ] && echo "VirtualAddrNetwork $TOR_VIRTUAL_ADDR_NETWORK"
[ "$TOR_VIRTUAL_ADDR_NETWORK_IPV4" ] && echo "VirtualAddrNetworkIPv4 $TOR_VIRTUAL_ADDR_NETWORK_IPV4"
[ "$TOR_VIRTUAL_ADDR_NETWORK_IPV6" ] && echo "VirtualAddrNetworkIPv6 $TOR_VIRTUAL_ADDR_NETWORK_IPV6"
